version: '3.8'

services:
  finbot-web:
    build:
      context: .
      args:
        # Truyền API Key vào lúc build (cần tạo file .env hoặc export biến môi trường trước khi chạy)
        - API_KEY=${API_KEY}
    container_name: finbot-web
    restart: always
    ports:
      - "6896:80"
    environment:
      - NODE_ENV=production
